config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios

  namespace :api do
    resources :boletos, only: [] do
      get :ventas, on: :member
    end
    resources :clientes, only: :index
    resources :corporaciones, only: :index
    resources :productos, only: :index
    resources :ventas, only: :show
  end

  resources :administradores, except: [:destroy]
  resources :armazones
  resources :clientes, except: [:destroy]
  resources :corporaciones
  resources :lentes
  resources :marcas
  resources :micas
  resources :tiendas
  resources :tratamientos
  resources :vendedores, except: [:destroy]
  resources :ventas

  root 'homes#index'
end

app/models/admin.rb
class Admin < Usuario
  before_create :establecer_cargo

  private

  def establecer_cargo
    self.cargo = 'admin'
  end
end

app/models/administrador.rb
class Administrador < Usuario
  before_create :establecer_cargo

  private

  def establecer_cargo
    self.cargo = 'admin'
  end
end

app/models/armazon.rb
class Armazon < Producto
  TIPOS = {
    'Armazón Completo'       => 'armazón completo',
    'Armazón de Tres Piezas' => 'armazón de tres piezas',
    'Ranurado'               => 'ranurado',
    'Sobrepuesto'            => 'sobrepuesto'
  }

  validates :tipo, presence: true
end

app/models/cliente.rb
class Cliente < ApplicationRecord
  include Domiciliable

  belongs_to :corporacion
  has_many :ventas

  validates :nombre, :corporacion_id, presence: true
  validates :nombre, uniqueness: { case_sensitive: false }

  scope :con_corporacion, -> { includes(:corporacion) }

  def self.buscar texto
    where("concat_ws(' ', nombre, telefono, rfc) ILIKE ?", "%#{texto&.squish}%")
  end

  def to_s
    nombre
  end
end

app/models/corporacion.rb
class Corporacion < Empresa
  has_many :clientes
end

app/models/domicilio.rb
class Domicilio < ApplicationRecord
  belongs_to :domiciliable, polymorphic: true

  validates :pais, :estado, presence: true

  def to_s
    "#{calle} ##{numero} \n #{colonia} #{codigo_postal} \n #{municipio}, #{estado}"
  end
end

app/models/empresa.rb
class Empresa < ApplicationRecord
  include Domiciliable
  mount_uploader :logotipo, LogotipoUploader

  validates :nombre, presence: true

  def to_s
    nombre
  end
end

app/models/lente.rb
class Lente < Producto
  TIPOS = {
    'Filtro UV'  => 'filtro uv',
    'Polarizado' => 'polarizado'
  }

  validates :tipo, presence: true
end

app/models/marca.rb
class Marca < ApplicationRecord
  validates :nombre, presence: true
  validates :nombre, uniqueness: { case_sensitive: false }

  has_many :productos

  def self.buscar texto
    where("concat_ws(' ', nombre, descripcion) ILIKE ?", "%#{texto&.squish}%")
  end

  def to_s
    nombre
  end
end

app/models/mica.rb
class Mica < Producto
  TIPOS = {
    'Bifocal'       => 'bifocal',
    'Blande'        => 'blande',
    'Cr'            => 'cr',
    'Hi-Index'      => 'hi-index',
    'Monofocal'     => 'monofocal',
    'Policarbonato' => 'policarbonato'
  }
end

app/models/pago.rb
class Pago < ApplicationRecord
  belongs_to :venta

  validates :efectivo, :anticipo, :cambio, presence: true
  validates :efectivo, :anticipo, numericality: { greater_than: 0 }
  validates :cambio, numericality: { greater_than_or_equal_to: 0 }
end

app/models/producto.rb
class Producto < ApplicationRecord
  mount_uploaders :imagenes, ImagenUploader

  belongs_to :marca
  belongs_to :usuario
  has_many :vendidos
  has_many :ventas, through: :vendidos

  validates :nombre, :codigo, :existencia, :precio_venta,
    :usuario, :type, :marca_id, presence: true
  validates :precio_venta, numericality: { greater_than: 0 }
  validates :codigo, uniqueness: { case_sensitive: false }

  scope :con_marca, -> { includes(:marca) }

  def self.buscar texto
    where("concat_ws(' ', codigo, nombre, tipo, type, existencia) ILIKE ?", "%#{texto&.squish}%")
  end

  def to_s
    "#{codigo} #{nombre}"
  end
end

app/models/tienda.rb
class Tienda < Empresa
  validates :logotipo, presence: true
end

app/models/tratamiento.rb
class Tratamiento < Producto
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  enum cargo: [:vendedor, :admin]

  has_many :armazones
  has_many :lentes
  has_many :micas
  has_many :tratamientos
  has_many :ventas

  validates :nombre, presence: true
  validates :nombre, uniqueness: { case_sensitive: false }

  def active_for_authentication?
    super && activo?
  end

  def inactive_message
    activo? ? super : :account_inactive
  end

  def to_s
    nombre.titleize
  end

  devise :database_authenticatable, :recoverable, :rememberable,
    :validatable, :trackable
end

app/models/vendedor.rb
class Vendedor < Usuario
end

app/models/vendido.rb
class Vendido < ApplicationRecord
  belongs_to :venta
  belongs_to :producto

  validates :cantidad, :precio_venta, :precio_compra,
    :descuento, :subtotal, presence: true

  validates :cantidad, :precio_venta, :subtotal,
    numericality: { greater_than: 0 }
  validates :precio_compra, numericality: { greater_than_or_equal_to: 0 }

  delegate :nombre, :codigo, :tipo, to: :producto, prefix: false,
    allow_nil: true

  default_scope { includes(:producto) }

  def to_s
    codigo
  end
end

app/models/venta.rb
class Venta < ApplicationRecord
  PRIMER_CODIGO = "0000000000017"

  before_save :comprobar_estado_de_pago
  before_create :asignar_siguiente_codigo!
  after_save :descontar_existencia_de_producto!

  belongs_to :cliente
  belongs_to :usuario
  has_many :vendidos, dependent: :destroy
  has_many :productos, through: :vendidos
  has_many :pagos, dependent: :destroy

  accepts_nested_attributes_for :vendidos
  accepts_nested_attributes_for :pagos

  validates :cliente, :fecha_entrega, :forma_de_pago, presence: true
  validates :total, numericality: { greater_than: 0 }

  scope :con_cliente, -> { includes(:cliente) }
  scope :con_pagos,   -> { includes(:pagos) }

  def self.buscar texto
    where("concat_ws(' ', codigo, total, descuento) ILIKE ?", "%#{texto&.squish}%")
  end

  def suma_precios_venta
    vendidos.map { |v| v.precio_venta * v.cantidad }.sum
  end

  def suma_descuentos
    vendidos.map(&:descuento).sum
  end

  def deuda
    total - suma_anticipos
  end

  def suma_anticipos
    pagos.map(&:anticipo).sum
  end

  def to_s
    codigo
  end

  private

  def comprobar_estado_de_pago
    self.saldada = anticipos_mayor_o_igual_que_total?
  end

  def anticipos_mayor_o_igual_que_total?
    suma_anticipos >= total
  end

  def asignar_siguiente_codigo!
    CodigoSiguienteServicio.new(self).asignar
  end

  def descontar_existencia_de_producto!
    ExistenciaDeProductoServicio.new(self).descontar if saldada?
  end

end

app/controllers/api/productos_controller.rb
class Api::ProductosController < ApplicationController
  def index
    @productos = Producto.buscar(params[:q]).page(params[:page])

    respond_to do |format|
      format.json { render :index, status: :ok, location: @productos.to_json }
    end
  end
end

app/helpers/lentes_helper.rb
module LentesHelper
end

app/helpers/marcas_helper.rb
module MarcasHelper

  def opciones_de_marcas
    Marca.all.map { |m| [m, m.id] }
  end

end

app/helpers/micas_helper.rb
module MicasHelper
end

app/helpers/productos_helper.rb
module ProductosHelper

  def estado_de_publicacion modelo
    content_tag :span, class: "badge #{badge_publicado(modelo)}" do
      modelo.publicado? ? 'PUBLICADO' : 'NO PUBLICADO'
    end
  end

  private

  def badge_publicado modelo
    modelo.publicado? ? 'badge-success' : 'badge-primary'
  end

end

app/views/productos/_form.html.haml
= simple_form_for producto do |f|
  .row
    .col-md-3
      = f.input :nombre
    .col-md-3
      = f.input :codigo
    .col-md-3
      = f.input :marca_id, collection: opciones_de_marcas
    .col-md-3
      - if tipos.any?
        = f.input :tipo, collection: tipos
    .col-md-3
      = f.input :existencia, as: :integer
    .col-md-3
      = f.input :precio_venta, as: :float
    .col-md-3
      - if usuario_es?(:admin, :optica)
        = f.input :precio_compra, as: :float
    .col-md-3.text-center
      = label_tag '¿Deseas publicar el producto?'
      = f.input :publicado
    .col-md-12
      = f.input :descripcion, as: :text
    .col-md-2
      = f.input :imagenes, as: :file, input_html: { multiple: true }
    .col-md-10
      - if producto.imagenes?
        - producto.imagenes.each do |imagen|
          = image_tag imagen.chica.url
    .block-content.block-content-full.block-content-sm.bg-body-light.font-size-sm
      .col-md-12
        = f.submit class: 'btn btn-alt-primary'

app/views/productos/_producto.html.haml
%table.table.table-hover.table-sm.table-vcenter
  %tr
    %th código:
    %td= producto.codigo
    %th nombre:
    %td= producto.nombre
  %tr
    %th existencia:
    %td= producto.existencia
    %th estado:
    %td= estado_de_publicacion producto
  %tr
    %th precio de venta:
    %td= number_to_currency producto.precio_venta
    - if usuario_es?(:admin, :optica)
      %th precio de compra:
      %td= number_to_currency producto.precio_compra
    - else
      %th
      %td
  %tr
    %th tipo de producto:
    %td= producto.tipo
    %th marca:
    %td= producto.marca
  %tr
    %th registrado el:
    %td= l producto.created_at, format: :long
    %th actualizado el:
    %td= l producto.updated_at, format: :long
  %tr
    %th descripción:
    %td= producto.descripcion
    %th
    %td

  %tr
    - producto.imagenes.each do |imagen|
      %td= image_tag imagen.chica.url

app/views/productos/_table.html.haml
.table-responsive
  %table.table.table-striped.table-hover.table-sm.table-vcenter
    %thead
      %tr
        %th código
        %th marca
        %th precio
        %th existencias
        %th tipo
        %th estado
        %th.text-center{:style => "width: 100px;"} Acciones
    %tbody
      - productos.each do |producto|
        %tr
          %td= producto.codigo
          %td= producto.marca
          %td= number_to_currency producto.precio_venta
          %td= producto.existencia
          %td= producto.tipo
          %td= estado_de_publicacion producto
          %td
            .btn-group
              = link_to producto, class: 'btn btn-alt-info' do
                %i.si.si-eye
                detalles
              = link_to [:edit, producto], class: 'btn btn-alt-warning' do
                %i.si.si-pencil
                editar
    %tfoot
      %tr
        %td{ colspan: 7 }
          .row
            .col-6
              = paginate productos
            .col-6
              .pull-right
                = page_entries_info productos

app/views/productos/index.html.erb
<h1>Productos</h1>

<%= link_to "crear producto", new_producto_path %>
<br/>
<%= link_to "regresar", root_path %>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-condensed table-hover">
    <thead>
      <tr>
        <th>nombre</th>
        <th>código</th>
      </tr>
    </thead>
    <tbody>
      <% @productos.each do |producto| %>
        <tr>
          <td><%= producto.nombre %></td>
          <td><%= producto.codigo %></td>
          <td>
            <%= link_to "detalles", producto %>
            <%= link_to "editar", [:edit, producto] %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>