config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios

  namespace :api do
    resources :boletos, only: [] do
      get :ventas, on: :member
    end
    resources :clientes, only: :index
    resources :corporaciones, only: :index
    resources :productos, only: :index
    resources :ventas, only: :show
  end

  resources :administradores, except: [:destroy]
  resources :armazones
  resources :clientes, except: [:destroy]
  resources :corporaciones
  resources :lentes
  resources :marcas
  resources :micas
  resources :tiendas
  resources :tratamientos
  resources :vendedores, except: [:destroy]
  resources :ventas

  root 'homes#index'
end

app/models/admin.rb
class Admin < Usuario
  before_create :establecer_cargo

  private

  def establecer_cargo
    self.cargo = 'admin'
  end
end

app/models/administrador.rb
class Administrador < Usuario
  before_create :establecer_cargo

  private

  def establecer_cargo
    self.cargo = 'admin'
  end
end

app/models/armazon.rb
class Armazon < Producto
  TIPOS = {
    'Armazón Completo'       => 'armazón completo',
    'Armazón de Tres Piezas' => 'armazón de tres piezas',
    'Ranurado'               => 'ranurado',
    'Sobrepuesto'            => 'sobrepuesto'
  }

  validates :tipo, presence: true
end

app/models/cliente.rb
class Cliente < ApplicationRecord
  include Domiciliable

  belongs_to :corporacion
  has_many :ventas

  validates :nombre, :corporacion_id, presence: true
  validates :nombre, uniqueness: { case_sensitive: false }

  scope :con_corporacion, -> { includes(:corporacion) }

  def self.buscar texto
    where("concat_ws(' ', nombre, telefono, rfc) ILIKE ?", "%#{texto&.squish}%")
  end

  def to_s
    nombre
  end
end

app/models/corporacion.rb
class Corporacion < Empresa
  has_many :clientes
end

app/models/domicilio.rb
class Domicilio < ApplicationRecord
  belongs_to :domiciliable, polymorphic: true

  validates :pais, :estado, presence: true

  def to_s
    "#{calle} ##{numero} \n #{colonia} #{codigo_postal} \n #{municipio}, #{estado}"
  end
end

app/models/empresa.rb
class Empresa < ApplicationRecord
  include Domiciliable
  mount_uploader :logotipo, LogotipoUploader

  validates :nombre, presence: true

  def to_s
    nombre
  end
end

app/models/lente.rb
class Lente < Producto
  TIPOS = {
    'Filtro UV'  => 'filtro uv',
    'Polarizado' => 'polarizado'
  }

  validates :tipo, presence: true
end

app/models/marca.rb
class Marca < ApplicationRecord
  validates :nombre, presence: true
  validates :nombre, uniqueness: { case_sensitive: false }

  has_many :productos

  def self.buscar texto
    where("concat_ws(' ', nombre, descripcion) ILIKE ?", "%#{texto&.squish}%")
  end

  def to_s
    nombre
  end
end

app/models/mica.rb
class Mica < Producto
  TIPOS = {
    'Bifocal'       => 'bifocal',
    'Blande'        => 'blande',
    'Cr'            => 'cr',
    'Hi-Index'      => 'hi-index',
    'Monofocal'     => 'monofocal',
    'Policarbonato' => 'policarbonato'
  }
end

app/models/pago.rb
class Pago < ApplicationRecord
  belongs_to :venta

  validates :efectivo, :anticipo, :cambio, presence: true
  validates :efectivo, :anticipo, numericality: { greater_than: 0 }
  validates :cambio, numericality: { greater_than_or_equal_to: 0 }
end

app/models/producto.rb
class Producto < ApplicationRecord
  mount_uploaders :imagenes, ImagenUploader

  belongs_to :marca
  belongs_to :usuario
  has_many :vendidos
  has_many :ventas, through: :vendidos

  validates :nombre, :codigo, :existencia, :precio_venta,
    :usuario, :type, :marca_id, presence: true
  validates :precio_venta, numericality: { greater_than: 0 }
  validates :codigo, uniqueness: { case_sensitive: false }

  scope :con_marca, -> { includes(:marca) }

  def self.buscar texto
    where("concat_ws(' ', codigo, nombre, tipo, type, existencia) ILIKE ?", "%#{texto&.squish}%")
  end

  def to_s
    "#{codigo} #{nombre}"
  end
end

app/models/tienda.rb
class Tienda < Empresa
  validates :logotipo, presence: true
end

app/models/tratamiento.rb
class Tratamiento < Producto
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  enum cargo: [:vendedor, :admin]

  has_many :armazones
  has_many :lentes
  has_many :micas
  has_many :tratamientos
  has_many :ventas

  validates :nombre, presence: true
  validates :nombre, uniqueness: { case_sensitive: false }

  def active_for_authentication?
    super && activo?
  end

  def inactive_message
    activo? ? super : :account_inactive
  end

  def to_s
    nombre.titleize
  end

  devise :database_authenticatable, :recoverable, :rememberable,
    :validatable, :trackable
end

app/models/vendedor.rb
class Vendedor < Usuario
end

app/models/vendido.rb
class Vendido < ApplicationRecord
  belongs_to :venta
  belongs_to :producto

  validates :cantidad, :precio_venta, :precio_compra,
    :descuento, :subtotal, presence: true

  validates :cantidad, :precio_venta, :subtotal,
    numericality: { greater_than: 0 }
  validates :precio_compra, numericality: { greater_than_or_equal_to: 0 }

  delegate :nombre, :codigo, :tipo, to: :producto, prefix: false,
    allow_nil: true

  default_scope { includes(:producto) }

  def to_s
    codigo
  end
end

app/models/venta.rb
class Venta < ApplicationRecord
  PRIMER_CODIGO = "0000000000017"

  before_save :comprobar_estado_de_pago
  before_create :asignar_siguiente_codigo!
  after_save :descontar_existencia_de_producto!

  belongs_to :cliente
  belongs_to :usuario
  has_many :vendidos, dependent: :destroy
  has_many :productos, through: :vendidos
  has_many :pagos, dependent: :destroy

  accepts_nested_attributes_for :vendidos
  accepts_nested_attributes_for :pagos

  validates :cliente, :fecha_entrega, :forma_de_pago, presence: true
  validates :total, numericality: { greater_than: 0 }

  scope :con_cliente, -> { includes(:cliente) }
  scope :con_pagos,   -> { includes(:pagos) }

  def self.buscar texto
    where("concat_ws(' ', codigo, total, descuento) ILIKE ?", "%#{texto&.squish}%")
  end

  def suma_precios_venta
    vendidos.map { |v| v.precio_venta * v.cantidad }.sum
  end

  def suma_descuentos
    vendidos.map(&:descuento).sum
  end

  def deuda
    total - suma_anticipos
  end

  def suma_anticipos
    pagos.map(&:anticipo).sum
  end

  def to_s
    codigo
  end

  private

  def comprobar_estado_de_pago
    self.saldada = anticipos_mayor_o_igual_que_total?
  end

  def anticipos_mayor_o_igual_que_total?
    suma_anticipos >= total
  end

  def asignar_siguiente_codigo!
    CodigoSiguienteServicio.new(self).asignar
  end

  def descontar_existencia_de_producto!
    ExistenciaDeProductoServicio.new(self).descontar if saldada?
  end

end

app/helpers/lentes_helper.rb
module LentesHelper
end

app/helpers/micas_helper.rb
module MicasHelper
end

app/views/layouts/partials/_alerts.html.haml
- unless flash.empty?
  - if flash[:notice]
    .alerta.alert.alert-success.alert-dismissable{:role => "alert"}
      %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
        %span{"aria-hidden" => "true"} ×
      %p.mb-0= notice
  - if flash[:alert]
    .alerta.alert.alert-danger.alert-dismissable{:role => "alert"}
      %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
        %span{"aria-hidden" => "true"} ×
      %p.mb-0= alert

app/views/layouts/partials/_footer.html.haml
%footer#page-footer.bg-white.opacity-0
  .content.py-20.font-size-xs.clearfix
    .float-right
      Hecho con
      %i.fa.fa-heart.text-pulse
      por
      %a.font-w600{:href => "https://twitter.com/javasgon?lang=es", :target => "_blank"} @javasgon
    .float-left
      %a.font-w600{:href => "https://goo.gl/po9Usv", :target => "_blank"} Codebase 2.1
      ©
      %span.js-year-copy 2019

app/views/layouts/partials/_navbar.html.haml
%body
  %p
    Header --&gt;
    %header#page-header
      / Header Content
      .content-header
        .content-header-section
          %button.btn.btn-circle.btn-dual-secondary{"data-action" => "sidebar_toggle", "data-toggle" => "layout", :type => "button"}
            %i.fa.fa-navicon
        / Right Section
        .content-header-section
          %i.fa.fa-user.d-sm-none
          %span.d-none.d-sm-inline-block
            = current_usuario
        / END Right Section
      / END Header Content

app/views/layouts/partials/_side_overlay.html.haml
%aside#side-overlay
  #side-overlay-scroll
    .content-header.content-header-fullrow.bg-primary-dark
      .content-header-section.align-parent
        %button.btn.btn-circle.btn-dual-secondary.align-v-r{"data-action" => "side_overlay_close", "data-toggle" => "layout", :type => "button"}
          %i.fa.fa-times.text-danger
        .content-header-item
          %a.img-link.mr-5{:href => "javascript:void(0)"}
            %img.img-avatar.img-avatar32{:alt => "", :src => "assets/media/avatars/avatar12.jpg"}/
          %a.align-middle.link-effect.text-white-op.font-w600{:href => "javascript:void(0)"} Admin
    .content-side
      .block.pull-t.pull-r-l
        .block-content.block-content-full.block-content-sm.bg-primary
          .row.text-center
            .col-4
              .font-size-sm.font-w600.text-uppercase.text-white-op Sales
              .font-size-h4.text-white 985
            .col-4
              .font-size-sm.font-w600.text-uppercase.text-white-op Tickets
              .font-size-h4.text-white 251
            .col-4
              .font-size-sm.font-w600.text-uppercase.text-white-op Projects
              .font-size-h4.text-white 39

app/views/layouts/partials/_sidebar.html.haml
%nav#sidebar
  #sidebar-scroll
    .sidebar-content
      .content-header.content-header-fullrow.px-15.bg-black-op-10
        .content-header-section.sidebar-mini-visible-b
          %span.content-header-item.font-w700.font-size-xl.float-left.animated.fadeIn
            %span.text-dual-primary-dark j
            %span.text-primary &amp;j
        / Normal Mode
        .content-header-section.text-center.align-parent.sidebar-mini-hidden
          %button.btn.btn-circle.btn-dual-secondary.d-lg-none.align-v-r{"data-action" => "sidebar_close", "data-toggle" => "layout", :type => "button"}
            %i.fa.fa-times.text-danger
          .content-header-item
            = link_to root_path, class: 'link-effect font-w700' do
              %span.font-size-xl.text-dual-primary-dark= tienda_actual
        / END Normal Mode
      / Side Navigation
      .content-side.content-side-full
        %ul.nav-main
          %li.nav-main-heading
            %span.sidebar-mini-visible MP
            %span.sidebar-mini-hidden menú principal
          %li
            = link_to [:new, :venta], class: ruta_actual(new_venta_path) do
              %i.fa.fa-shopping-cart
              %span.sidebar-mini-hide Punto de venta
          %li
            = link_to [:ventas], class: ruta_actual(ventas_path) do
              %i.fa.fa-history
              %span.sidebar-mini-hide Historial de ventas
          %li.nav-main-heading
            %span.sidebar-mini-visible CS
            %span.sidebar-mini-hidden catálogos
          %li
            = link_to [:armazones], class: ruta_actual(armazones_path) do
              %i.fa.fa-adjust
              %span.sidebar-mini-hide Armazones
          %li
            = link_to [:lentes], class: ruta_actual(lentes_path) do
              %i.si.si-eyeglasses
              %span.sidebar-mini-hide Lentes
          %li
            = link_to [:micas], class: ruta_actual(micas_path) do
              %i.fa.fa-clone
              %span.sidebar-mini-hide Micas
          %li
            = link_to [:tratamientos], class: ruta_actual(tratamientos_path) do
              %i.fa.fa-bookmark
              %span.sidebar-mini-hide Tratamientos
          %li
            = link_to [:clientes], class: ruta_actual(clientes_path) do
              %i.fa.fa-users
              %span.sidebar-mini-hide Clientes
          %li
            = link_to [:corporaciones], class: ruta_actual(corporaciones_path) do
              %i.fa.fa-list
              %span.sidebar-mini-hide Corporaciónes
          %li
            = link_to [:marcas], class: ruta_actual(marcas_path) do
              %i.fa.fa-asterisk
              %span.sidebar-mini-hide Marcas

          - if usuario_es?(:admin, :optica)
            %li.nav-main-heading
              %span.sidebar-mini-visible CF
              %span.sidebar-mini-hidden configuración
            %li
              = link_to [:administradores], class: ruta_actual(administradores_path) do
                %i.fa.fa-users
                %span.sidebar-mini-hide Administradores
            %li
              = link_to [:vendedores], class: ruta_actual(vendedores_path) do
                %i.fa.fa-users
                %span.sidebar-mini-hide Vendedores
            %li
              = link_to [:tiendas], class: ruta_actual(tiendas_path) do
                %i.fa.fa-shopping-bag
                %span.sidebar-mini-hide Tienda
      .content-side
        %ul.nav-main
          %li
            = link_to destroy_usuario_session_path do
              %i.fa.fa-sign-out
              %span.sidebar-mini-hide cerrar sesión
      / END Side Navigation

app/views/shared/_buscador.html.haml
= form_tag recursos_ruta, method: :get, class: 'form-inline' do
  = text_field_tag :q, params[:q], placeholder: 'buscar',
    class: 'form-control mb-2 mr-sm-2 mb-sm-0'
  = button_tag type: 'submit', class: "btn btn-alt-primary"  do
    %i.fa.fa-search
    buscar